### ISSUE TITLE
Modificar H1 con el nombre y agregar subtitulo correspondiente como H3

### ISSUE THREAD

**Issue by charlos** [charlos/mi-cv#2]
Modificar h1 segun imagen
https://es.bestfreehtmlcsstemplates.com/plantillas/91/resume-una-plantilla-de-cv-gratis

**Comment by jcdavidarg** [comment]
señor carlos, no faltaria modificar el h2?

**Comment by charlos** [comment]
Estimado, muy buena observacion.
Ya mismo modifico la descripcion de issue

**Comment by charlos** [comment]
Agregar el subtitulo como un h3 por favor

**Comment by jcdavidarg** [comment]
Objetivo terminado, solicito pull request
