### ISSUE TITLE
Crear elementos basicos HTML

### ISSUE THREAD

**Issue by charlos** [charlos/mi-cv#6]
Se deben crear los elementos basicos HTML para ir maquetando la seccion ABOUT del CV segun la [imagen](https://cdn.bestfreehtmlcsstemplates.com/uploads/templates-images/ae03c777733e89b082471e5f46d522e3.jpeg)

**Comment by jcdavidarg** [comment]
Perfecto, manos a la obra

**Comment by jcdavidarg** [comment]
se maqueteó html sección about y consecuentemente seccion de presentacion
